version: '3'

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    environment:
      CLI_JAVA_OPTS: "-Xms2g -Xmx2g"
      bootstrap.memory_lock: true
      discovery.type: "single-node"
      xpack.security.enabled: true
      xpack.security.enrollment.enabled: true
      ELASTIC_PASSWORD: "EsNocmt2024"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - 10.27.0.2:9200:9200
      - 10.27.0.2:9300:9300
    networks:
      - forensic-net
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:    
      resources:
          limits:
            cpus: '2.0'
          reservations:
            cpus: '1.0'

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    container_name: kibana
    environment:
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: d1a66dfd-c4d3-4a0a-8290-2abcb83ab3aa
      ELASTICSEARCH_USERNAME: "nocmt"
      ELASTICSEARCH_PASSWORD: 'EsNocmt2024'
      xpack.security.enabled: true
    ports:
      - 10.27.0.2:5601:5601
    networks:
      - forensic-net
    deploy:    
      resources:
          limits:
            cpus: '2.0'
          reservations:
            cpus: '1.0'
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - 10.27.0.2:9191:9191
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      - elasticsearch
    networks:
      - forensic-net

volumes:
  elastic_data:
networks:
  forensic-net:
    driver: bridge
# volumes:
#   mongodata : ~/ForensicDB
# networks:
#   forensic-net:
#     driver: bridge